# /terraform/modules/rds/secrets.tf
resource "random_password" "db_password" {
  length           = 16
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

# Random suffix to avoid recovery-wait conflicts when destroy→apply cycles reuse the same secret name
resource "random_id" "db_secret_suffix" {
  byte_length = 4
}

resource "aws_secretsmanager_secret" "db_password" {
  name                    = "membership-blog-db-password-${random_id.db_secret_suffix.hex}"
  description             = "Aurora master password auto-generated by Terraform"
  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "db_password" {
  secret_id     = aws_secretsmanager_secret.db_password.id
  secret_string = random_password.db_password.result
}
